---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgBdxNM9zCyqRkLNGMNEEumz7+HYszQFvJro4EoLO1bkxfVGZW7udg0H+5Mscv2Gtc1ZEm/8oinw/3gYf8e92g0r8QF9iEPYMfvHYIZ43en2Q4rKyWXvb9tsCT+8XBea3ud9NZu95YwaU5ZHNluwPeC3WTxAye+siLoFdOTr94Y5XFImptv68PnWMXHSJa384qCaGAXnTe6m76y6BiL7RBDwt2ZJzUCmQknIJVwX86iSF18yKuohQ3RRKWczIGkIKoRbG+kmMu+U14ceTA5U3YrmIwNgIZPqjXatt5b9Hrl/jRVL0VohTbRdDlrS2ncR2dXFyDod6V5Gqq2rcyWzV0qmG30DF1PHuT1GZ6dphNPTxzrx6OMb9U49n8RVFs7IOExOVzy8andn48SCyaTzSAfW4nzHpzA4q0GJKTQtUkKyhcjmw6gf8S0jydgRdpteF/eDnc5tHQmonzZZmRPm7341qWdzxV1umqFy24c+NEkMIFpORQmHeAS2mbzdbjI+/GVaZUpC/0CIZKJbUPTcX3+Z/Ajdgd+RE951AFbfjYxkE9jAWWD/OXluNaiMsS3Eso+ZqgQ8+bL47KZurKOQnrPB3+CMQxFbDfybiyuFtlRDI0w5addxbauxOc10sysUQXccmrXzP/0PpKiGQSjDIFIdpK6slN4fWLGuBm8C0FnC+CvcP9VLZsOX+sW6lwvwyWGXKj7KiG4/UMJXiQ==
    username: AgBiUzFSXjo4H0E17BsN3MgDo9Ez81V8F8F9MR4IdpU0zYVjJWv2iK2izr5IUu6DPlJQFGzAt5IUOLQZ7/ABhHUcCB5tRSUz13LjuJN9AIWlq+51jv5SeWrFgygiMbyqw0tFUJRsPCHRDomKevpPj+esed8On071zKHYhEueAXY7F8R/zwLtfoY3PUnQjss2P1VAoItePa/3dk7RO0GZTUS+iz7X2l4i29XXXygwBcTXwWqOZSTOKCGUMPkPINd5fze1Tv2mFn/YBm7s4UTESRaOY59e2gi39SUPwbF/w5o+v8V09fMVvDAThjIjlodiQr0Mb3fQTgajUv/1oC4B8c0fV2w7ap3oQNZOE9ku3Ymp1pl0xOjSPW6gFk9h8XeykI+AmsN4eqi+vFrDSEllP1pnzELp4otW6Gr10YwZV7HPToN2SFCKGeyW26+UIv/Xx8OQcPymI2x0EsrOW1elVftqObij/DT32yaNhryh/i+lCOj1OO3FG68mGoiYCaIiiSC8Pw46+eIiQKTHpdh/bbnOaI6okKMMzHMzZ24XlGGoJSelO3w9mJsoFDJ1DVa2j1K2EAf/OaLoMURXUpqXJmN/su/nbG6ojlahHWDz5KD3QHHIArQU1gLtF/WFvcZwnjqpmxbN8EC3zHZTIeA+mjlbuHFQel8gn43+yJqPOJWO1rTrrS1HpWVi6qBrmEPXg4Dx2fLynw==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
